apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 2
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: myapp
          image: anais1210/myapp:latest
          ports:
            - containerPort: 8080
